sonar.projectKey=your_org_express
sonar.organization=your_sonarcloud_org
sonar.projectName=express (Backend)
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  **/node_modules/**, \
  **/coverage/**, \
  **/*.min.js, \
  **/dist/**

sonar.coverage.exclusions=\
  **/index.js
