name: AWS CLI Execution

on:
  workflow_dispatch: 

permissions:
  id-token: write
    
jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:             
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4  
        with:
          role-to-assume: ${{ vars.AWS_ASSUME_ROLE }}
          aws-region: ${{ vars.AWS_REGION }} 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image & Push to ECR
        run: aws cloudformation delete-stack --stack-name ecs-fargate-service --role-arn arn:aws:iam::623900187958:role/github_ecr_role


